// End-to-end: fresh user → onboarding → swipes → DNA → avatar → match → detail → back → reload resumes.
import { chromium, devices } from 'playwright'

const base = process.argv[2] ?? 'http://localhost:5179/'
const out = process.argv[3] ?? '/tmp/flow'
const browser = await chromium.launch()
const ctx = await browser.newContext({
  ...devices['iPhone 14'],
  deviceScaleFactor: 2,
  locale: 'de-DE', // the steps read German texts; English has its own step (I1)
  permissions: ['clipboard-read', 'clipboard-write', 'geolocation'],
  geolocation: { latitude: 49.2386, longitude: 9.1016 }, // Bad Rappenau – real regional data (R4)
})
const page = await ctx.newPage()
const errors = []
page.on('pageerror', (e) => errors.push(String(e)))
page.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
const step = async (name, fn) => {
  try {
    await fn()
    console.log('ok  ', name)
  } catch (e) {
    console.log('FAIL', name, '-', String(e).split('\n')[0])
    await page.screenshot({ path: `${out}-fail.png` })
    await browser.close()
    process.exit(1)
  }
}
const m = page.locator('main')
const see = (t) => m.getByText(t, { exact: false }).first().waitFor({ timeout: 4000 })

await page.goto(base, { waitUntil: 'load' })
await step('welcome', () => see('Erst Biere daten'))
await step('to howto', async () => { await m.getByText("Los geht's").click(); await see('Schritt 1 von 1') })
await step('age gate blocks', async () => { await m.getByText('Erstes Date starten').click(); await see('Kurz das Häkchen') })
await step('confirm age + start', async () => {
  await m.getByText('Ich bin mindestens 18').click()
  await m.getByText('Erstes Date starten').click()
  await see('Karte ziehen')
})
await step('help sheet opens and closes', async () => {
  await m.getByLabel('Wie war das nochmal?').click()
  await see('So swipst du')
  await m.getByText('Verstanden').click()
  await m.getByText('So swipst du').waitFor({ state: 'detached', timeout: 2000 })
})
await step('tap opens detail and back', async () => {
  const card = m.locator('[class*="slot"]').first()
  await card.click()
  await see('Ihr im Vergleich')
  await m.getByLabel('Zurück').click()
  await see('übrig')
})
await step('6 swipes via keyboard + buttons', async () => {
  for (const k of ['ArrowRight', 'ArrowLeft', 'ArrowUp', 'ArrowDown']) { await page.keyboard.press(k); await page.waitForTimeout(450) }
  await m.getByLabel('Kenne ich', { exact: true }).click(); await page.waitForTimeout(450)
  await m.getByLabel('Mag ich', { exact: true }).click(); await page.waitForTimeout(450)
  await see('DNA auswerten')
  await see('54 übrig')
})
await step('undo via button and Backspace', async () => {
  await m.getByLabel('Zurückholen').click()
  await see('Zurückgeholt'); await see('55 übrig')
  await page.keyboard.press('ArrowRight'); await page.waitForTimeout(450)
  await see('54 übrig')
  await page.keyboard.press('Backspace'); await page.waitForTimeout(450)
  await see('55 übrig')
  await page.keyboard.press('ArrowRight'); await page.waitForTimeout(450)
  await see('54 übrig')
})
await step('analyze → dna', async () => {
  await m.getByText('DNA auswerten').click()
  await see('Bier-DNA wird sequenziert')
  await page.waitForTimeout(3300)
  await see('entschlüsselt')
  await see('Neugier-Faktor')
})
await step('dna → avatar', async () => { await m.getByText('Wer bin ich').click(); await see('Du bist') })
await step('share card downloads as PNG', async () => {
  const [dl] = await Promise.all([page.waitForEvent('download', { timeout: 10000 }), m.getByLabel('Als Bild teilen').click()])
  if (!dl.suggestedFilename().endsWith('.png')) throw new Error('unexpected file ' + dl.suggestedFilename())
  await dl.saveAs(`${out}-sharecard.png`)
})
await step('avatar → match', async () => {
  await m.getByText('Mein Bier-Match zeigen').click()
  await see('Bier-Kompatibilität'); await page.waitForTimeout(1300)
  await page.screenshot({ path: `${out}-match.png` })
})
await step('match → detail → rate there', async () => {
  await m.getByText('Entdecken').click()
  await see('Wie steht ihr zueinander')
  await m.getByRole('button', { name: 'Will probieren' }).click()
  await see('Probierliste')
  await m.getByText('Zurückholen').click()
  await see('Zurückgeholt')
  await m.getByRole('button', { name: 'Will probieren' }).click()
})
await step('back to match, weiterswipen shows tabs', async () => {
  await m.getByLabel('Zurück').click()
  await m.getByText('Weiterswipen').click()
  await see('Swipen'); await see('Profil')
})
await step('profile shows history + achievement', async () => {
  await m.getByText('Profil', { exact: true }).click()
  await see('Erstes Date'); await see('Jever Pilsener')
  await page.screenshot({ path: `${out}-profile.png` })
})
await step('spiele: bier-quartett, one round against the bot', async () => {
  await m.getByText('Spiele', { exact: true }).click()
  await see('Bier-Quartett')
  await m.getByRole('button', { name: /Gegen den Kneipen-Bot/ }).click()
  await see('Runde 1 von 30')
  await m.getByRole('button', { name: /^Bittere/ }).click()
  await see('Du sagst: Bittere!')
  await page.screenshot({ path: `${out}-quartett.png` })
  await m.getByRole('button', { name: 'Weiter' }).click()
  page.once('dialog', (d) => d.accept())
  await m.getByRole('button', { name: 'Spiel beenden' }).click()
  await see('Noch nie gespielt') // an abandoned game doesn't count
  await m.getByText('Profil', { exact: true }).click()
})
await step('impressum & datenschutz from profile, back', async () => {
  await m.getByRole('button', { name: 'Impressum & Datenschutz' }).click()
  await see('Kurz gesagt'); await see('Geräte-Sync (nur wenn du ihn einschaltest)'); await see('Feedback („Wünsch dir was!“)'); await see('Bier melden („Bier fehlt? Eintragen“)')
  await page.screenshot({ path: `${out}-legal.png` })
  await m.getByLabel('Zurück').click()
  await see('Erstes Date')
})
await step('feedback: sheet validates, sends type + text + build (request stubbed – no real issue)', async () => {
  let sent = null
  await page.route('**/rest/v1/feedback', (r) => {
    sent = r.request().postDataJSON()
    return r.fulfill({ status: 201, body: '' })
  })
  await m.getByRole('button', { name: /Wünsch dir was!/ }).click()
  await see('ohne Namen öffentlich')
  await m.getByRole('radio', { name: /Fehler/ }).click()
  await m.getByLabel('Deine Nachricht').fill('ab')
  await m.getByRole('button', { name: 'Abschicken' }).click()
  await see('Ein paar Worte mehr')
  await m.getByLabel('Deine Nachricht').fill('E2E: Flow-Test, bitte ignorieren')
  await page.screenshot({ path: `${out}-feedback.png` })
  await m.getByRole('button', { name: 'Abschicken' }).click()
  await see('Prost & danke!')
  if (sent?.type !== 'bug' || sent?.message !== 'E2E: Flow-Test, bitte ignorieren' || !sent?.app_version || !/ · (App|Browser)$/.test(sent?.platform ?? ''))
    throw new Error('unexpected payload ' + JSON.stringify(sent))
  if (Object.keys(sent).sort().join() !== 'app_version,message,platform,type') throw new Error('extra fields ' + Object.keys(sent))
  await m.getByRole('button', { name: 'Schließen' }).click()
  await page.unroute('**/rest/v1/feedback')
})
await step('probierliste: tried → verdict removes it', async () => {
  await m.getByText('Matches', { exact: true }).click()
  await m.getByRole('tab', { name: 'Probierliste' }).click()
  await see('Vorgemerkt')
  const before = await m.getByRole('button', { name: 'Probiert!' }).count()
  if (before < 1) throw new Error('empty Probierliste')
  await m.getByRole('button', { name: 'Probiert!' }).first().click()
  await see("Und? Wie war's?")
  await page.screenshot({ path: `${out}-ratesheet.png` })
  await m.getByRole('button', { name: /Mag ich/ }).click()
  await m.getByText("Und? Wie war's?").waitFor({ state: 'detached', timeout: 2000 })
  const after = await m.getByRole('button', { name: 'Probiert!' }).count()
  if (after !== before - 1) throw new Error(`expected ${before - 1} left, got ${after}`)
})
await step('swipe header shows next match chip → detail', async () => {
  await m.getByText('Swipen', { exact: true }).click()
  await m.getByLabel(/Nächstes Match/).click()
  await see('Ihr im Vergleich')
  await m.getByLabel('Zurück').click()
})
await step('reload resumes on deck with tabs', async () => {
  await page.reload({ waitUntil: 'load' })
  await see('übrig'); await see('Swipen')
  await m.getByText('Bier-DNA', { exact: true }).click()
  await see('entschlüsselt')
})
let regionalBeer = ''
await step('regional finder: position → nearby beers → sheet → Probieren', async () => {
  await m.getByRole('button', { name: /Biere aus deiner Nähe/ }).click()
  await m.getByRole('button', { name: 'Mein Standort' }).click()
  await m.getByText(/\d+ Biere? · \d+ Brauereie?n? im Umkreis/).waitFor({ timeout: 20000 })
  await m.getByText('Stil-Schätzung').first().waitFor()
  await page.screenshot({ path: `${out}-regional.png` })
  await m.locator('button[class*="reco"]').first().click()
  await see('Hauptbiere')
  const dialog = m.locator('[role=dialog]')
  regionalBeer = (await dialog.locator('[class*="recoName"]').first().innerText()).trim()
  await dialog.getByRole('button', { name: 'Probieren', exact: true }).first().click()
  await dialog.getByRole('button', { name: 'Vorgemerkt', exact: true }).first().waitFor()
  await page.keyboard.press('Escape')
  await m.getByLabel('Zurück').click()
  await see('entschlüsselt')
})
await step('beer report: brewery sheet → „Bier fehlt?“ → validated, sent (request stubbed – no real issue)', async () => {
  let sent = null
  await page.route('**/rest/v1/beer_submissions', (r) => {
    sent = r.request().postDataJSON()
    return r.fulfill({ status: 201, body: '' })
  })
  await m.getByRole('button', { name: /Biere aus deiner Nähe/ }).click()
  await m.locator('button[class*="reco"]').first().click()
  const dialog = m.locator('[role=dialog]')
  const brewery = (await dialog.locator('h2, [class*="title"]').first().innerText()).trim()
  await dialog.getByRole('button', { name: /Bier fehlt\? Eintragen/ }).click()
  await see('Ein Link reicht')
  await m.getByRole('button', { name: 'Melden' }).click()
  await see('eins davon brauchen wir')
  await m.getByLabel('Name des Biers').fill('E2E Testbier')
  await m.getByLabel('Bierstil').selectOption('Kellerbier')
  await m.getByLabel('Alkohol (% vol)').fill('5,2')
  await page.screenshot({ path: `${out}-beer-report.png` })
  await m.getByRole('button', { name: 'Melden' }).click()
  await see('Deine Meldung ist unterwegs')
  if (!sent?.brewery_id || sent.brewery_name !== brewery || sent.beer_name !== 'E2E Testbier' || sent.style !== 'Kellerbier' || sent.abv !== 5.2)
    throw new Error('unexpected payload ' + JSON.stringify(sent))
  if (Object.keys(sent).sort().join() !== 'abv,app_version,beer_name,brewery_id,brewery_name,platform,style') throw new Error('extra fields ' + Object.keys(sent))
  await m.getByRole('button', { name: 'Schließen' }).click()
  await page.unroute('**/rest/v1/beer_submissions')
  await m.getByLabel('Zurück').click()
  await see('entschlüsselt')
})
await step('regional beer stays on the Probierliste after a reload', async () => {
  await page.reload({ waitUntil: 'load' })
  await m.getByText('Matches', { exact: true }).click()
  await m.getByRole('tab', { name: 'Probierliste' }).click()
  await m.getByText(regionalBeer, { exact: true }).first().waitFor({ timeout: 4000 })
  await m.getByRole('tab', { name: 'Nähe' }).click()
  await m.getByLabel('PLZ').fill('74906')
  await m.getByRole('button', { name: 'Los' }).click()
  await see('Rund um 74906')
  await m.getByText('Bier-DNA', { exact: true }).click()
})
await step('regional mode: switch in the finder → every third swipe card is from nearby', async () => {
  await m.getByRole('button', { name: /Biere aus deiner Nähe/ }).click()
  await m.getByText(/\d+ Biere? · \d+ Brauereie?n? im Umkreis/).waitFor({ timeout: 20000 })
  await m.getByLabel(/Regional-Modus im Swipe-Deck/).check()
  await m.getByLabel('Zurück').click()
  await m.getByText('Swipen', { exact: true }).click()
  const badge = m.getByText(/^Aus deiner Nähe · /)
  await badge.first().waitFor({ timeout: 4000 })
  await page.screenshot({ path: `${out}-regional-deck.png` })
  for (let i = 0; i < 3; i++) await page.keyboard.press('k')
  await badge.first().waitFor({ timeout: 4000 })
  await m.getByText('Bier-DNA', { exact: true }).click()
})
let buddyLink = ''
await step('buddy invite copies a link', async () => {
  await m.getByText('Matches', { exact: true }).click()
  await m.getByRole('tab', { name: /Menschen/ }).click()
  await m.getByRole('button', { name: 'Buddy einladen' }).click()
  await see('Link kopiert')
  const text = await page.evaluate(() => navigator.clipboard.readText())
  buddyLink = text.slice(text.indexOf('http'))
  if (!buddyLink.includes('?buddy=')) throw new Error('no buddy link in clipboard: ' + text)
})
await step('export → reset → import on welcome restores the profile', async () => {
  await m.getByText('Profil', { exact: true }).click()
  const [dl] = await Promise.all([page.waitForEvent('download', { timeout: 10000 }), m.getByText('Profil exportieren').click()])
  const file = `${out}-profile.json`
  await dl.saveAs(file)
  page.once('dialog', (d) => d.accept())
  await m.getByText('Profil zurücksetzen').click()
  await see('Erst Biere daten')
  await m.getByLabel('Profil importieren').setInputFiles(file)
  await see('Willkommen zurück')
  await see('übrig')
  await m.getByText('Profil', { exact: true }).click()
  await see('Jever Pilsener')
})
await step('reset clears everything', async () => {
  await m.getByText('Profil', { exact: true }).click()
  page.once('dialog', (d) => d.accept())
  await m.getByText('Profil zurücksetzen').click()
  await see('Erst Biere daten')
  await page.reload({ waitUntil: 'load' })
  await see('Erst Biere daten')
})
await step('buddy link: new user is invited, onboards, sees the comparison', async () => {
  await page.goto(buddyLink, { waitUntil: 'load' })
  await see('hat dich eingeladen')
  if (page.url().includes('buddy=')) throw new Error('buddy param not removed from URL')
  await m.getByText("Los geht's").click()
  await m.getByText('Ich bin mindestens 18').click()
  await m.getByText('Erstes Date starten').click()
  for (let i = 0; i < 6; i++) { await page.keyboard.press(i % 2 ? 'ArrowLeft' : 'ArrowRight'); await page.waitForTimeout(450) }
  await m.getByText('DNA auswerten').click()
  await page.waitForTimeout(3300)
  await m.getByText('Vergleich ansehen').click()
  await see('Du + Buddy #')
  await see('Bier-DNA-Match')
  await page.screenshot({ path: `${out}-buddy.png` })
})
await step('English: an English browser gets the English app, the welcome link switches languages', async () => {
  const enCtx = await browser.newContext({ ...devices['iPhone 14'], deviceScaleFactor: 2, locale: 'en-US' })
  const en = await enCtx.newPage()
  en.on('pageerror', (e) => errors.push(String(e)))
  const em = en.locator('main')
  const enSee = (t) => em.getByText(t, { exact: false }).first().waitFor({ timeout: 4000 })
  await en.goto(base, { waitUntil: 'load' })
  await enSee('Date beers first')
  if ((await en.locator('html').getAttribute('lang')) !== 'en') throw new Error('html lang is not en')
  // the link on the welcome screen switches (and remembers) the language
  await Promise.all([en.waitForEvent('load'), em.getByText('Deutsch', { exact: true }).click()])
  await enSee('Erst Biere daten')
  await Promise.all([en.waitForEvent('load'), em.getByText('English', { exact: true }).click()])
  await enSee('Date beers first')
  await em.getByText("Let's go").click()
  await em.getByText('I am at least 18').click()
  await em.getByText('Start the first date').click()
  for (let i = 0; i < 3; i++) { await en.keyboard.press('ArrowRight'); await en.waitForTimeout(450) }
  await enSee('left')
  await enSee("Don't know")
  await en.screenshot({ path: `${out}-english.png` })
  await en.reload({ waitUntil: 'load' })
  await enSee('left')
  await enCtx.close()
})
if (errors.length) console.log('PAGE ERRORS:\n' + errors.join('\n'))
else console.log('no page errors')
await browser.close()
