"""Glyph advance widths for the bottle label fonts → src/domain/bottles/metrics.ts.

The bottle generator sets label text without a DOM, so it needs the real widths.
Run once after a font package update (venv with `pip install fonttools brotli`):
    python3 tools/bottles/metrics.py
"""
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

CHARS = ''.join(chr(c) for c in range(32, 127)) + 'ÄÖÜäöüß·éèàáâçñ'
NM = 'node_modules/@fontsource'


def widths(font):
    cmap, hmtx, upm = font.getBestCmap(), font['hmtx'], font['head'].unitsPerEm
    return [round(hmtx[cmap[ord(c)]][0] * 1000 / upm) if ord(c) in cmap else 0 for c in CHARS]


fonts = {}
for w in (600, 700, 800):
    f = TTFont(f'{NM}-variable/bricolage-grotesque/files/bricolage-grotesque-latin-standard-normal.woff2')
    fonts[f'sans{w}'] = widths(instancer.instantiateVariableFont(f, {'wght': w, 'opsz': 96, 'wdth': 100}))
fonts['serif'] = widths(TTFont(f'{NM}/young-serif/files/young-serif-latin-400-normal.woff2'))
fonts['gothic'] = widths(TTFont(f'{NM}/unifrakturcook/files/unifrakturcook-latin-700-normal.woff2'))

out = [
    '// Generated by tools/bottles/metrics.py – glyph advance widths in 1/1000 em. Do not edit.',
    '',
    f'export const METRIC_CHARS = {CHARS!r}'.replace("'", "'"),
    '',
    'export const METRICS: Record<string, readonly number[]> = {',
]
for k, v in fonts.items():
    out.append(f'  {k}: [{",".join(map(str, v))}],')
out.append('}')
out.append('')
open('src/domain/bottles/metrics.ts', 'w').write('\n'.join(out))
print('ok', {k: len(v) for k, v in fonts.items()})
